blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://discord.com/users/335813464079728650
    about: You can send me messages directly.
  - name: Itch.io
    url: https://mestre-tramador.itch.io
    about: You can search more on my Itch.io profile.
  - name: LinkedIn
    url: https://www.linkedin.com/in/mestre-tramador
    about: You can contact me formally if you want to.
